name: Daily Shorts Generator

on:
  workflow_dispatch: # Allows manual button click
  schedule:
    - cron: '0 10,22 * * *' # Runs at 10 AM and 10 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          cat /etc/ImageMagick-6/policy.xml | sed 's/none/read,write/g' | sudo tee /etc/ImageMagick-6/policy.xml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run Generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        run: python main.py

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-short
          path: final_short.mp4
